// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuLDDK_aPnZPP1MNHnFsDkMtwhqpHxjGM',
    appId: '1:353951566948:web:457ab0720e816a71a8a371',
    messagingSenderId: '353951566948',
    projectId: 'rt-todo-app',
    authDomain: 'rt-todo-app.firebaseapp.com',
    storageBucket: 'rt-todo-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1pQq5g2KEri_xib8zcNe2J48rfBRJluE',
    appId: '1:353951566948:android:9a45d91e7c598c5ca8a371',
    messagingSenderId: '353951566948',
    projectId: 'rt-todo-app',
    storageBucket: 'rt-todo-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvrhszq5x0ezmXIRGo8ztlIu16wVTsK1g',
    appId: '1:353951566948:ios:585bf5ccc912bb34a8a371',
    messagingSenderId: '353951566948',
    projectId: 'rt-todo-app',
    storageBucket: 'rt-todo-app.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvrhszq5x0ezmXIRGo8ztlIu16wVTsK1g',
    appId: '1:353951566948:ios:61f5d986c722603ca8a371',
    messagingSenderId: '353951566948',
    projectId: 'rt-todo-app',
    storageBucket: 'rt-todo-app.appspot.com',
    iosBundleId: 'com.example.todoApp.RunnerTests',
  );
}
